/-
  Golden tests for the SoPlex API ↔ canonical-form translation, one
  per cell of the row-sense × column-status matrix, for both objective
  senses. See `docs/accessors.md` for the accessor sign documentation
  this file pins down. Closes #18.

  Each case fixes a canonical (minimisation) LP and the expected
  `DualBundle` for it; we then exercise the case twice — once with
  `sense := .minimize` (passing `cCanon` directly), once with
  `sense := .maximize` (passing `-cCanon`). Both runs go through
  `canonicalize` and so should report the same canonical dual; the
  reported `Solution.objective` flips sign between the two senses
  (the max-sense cross-checks `canonicalize`'s sign discipline).

  Per-case sanity:
    * `solveExact` returns `.optimal` with the expected primal vector.
    * The reported objective matches `expectedObjCanon` (min sense)
      or `-expectedObjCanon` (max sense).
    * The returned `DualBundle` equals `expectedDual` exactly.
    * `checkOptimal pCanon x dual = true` — the pure-Lean verifier
      independently certifies the bridge's translation.
-/

import LeanSoplex

open LeanSoplex LeanSoplex.Verify

namespace AccessorGoldens

inductive Outcome
  | ok
  | fail (msg : String)

/-- A single golden case, expressed in canonical (minimisation) form. -/
structure CoreCase where
  name : String
  numVars : Nat
  numConstraints : Nat
  /-- Objective coefficient vector for the canonical (min) LP. The
      max-sense run is generated by negating this. -/
  cCanon : Array Rat
  a : Array (Nat × Nat × Rat)
  rowBounds : Array (Option Rat × Option Rat)
  colBounds : Array (Option Rat × Option Rat)
  /-- `some x*` to assert primal equality; `none` to skip (e.g. for
      genuinely degenerate optima like free-row × free-col where every
      `x` is feasible-and-optimal). -/
  expectedX : Option (Array Rat)
  /-- Optimal `c · x` for the canonical (min) form. -/
  expectedObjCanon : Rat
  expectedDual : DualBundle numConstraints numVars

private def noPresolve (sense : ObjSense) : Options :=
  { ({} : Options) with sense, presolve := false, verbose := false, precisionBoost := false }

private def dualEq {m₁ n₁ m₂ n₂ : Nat}
    (a : DualBundle m₁ n₁) (b : DualBundle m₂ n₂) : Bool :=
  a.rowLower.toArray == b.rowLower.toArray
    && a.rowUpper.toArray == b.rowUpper.toArray
    && a.colLower.toArray == b.colLower.toArray
    && a.colUpper.toArray == b.colUpper.toArray

/-- Run one core case in a given sense. For `.maximize` the
    user-facing `c` is negated so that the canonical (post-
    `canonicalize`) LP is the same as in the `.minimize` run, and the
    expected user-facing objective flips sign. -/
private def runOne (case : CoreCase) (sense : ObjSense) : Outcome :=
  let cUser : Array Rat :=
    match sense with
    | .minimize => case.cCanon
    | .maximize => case.cCanon.map Neg.neg
  let expectedObjUser : Rat :=
    match sense with
    | .minimize => case.expectedObjCanon
    | .maximize => -case.expectedObjCanon
  let p : Problem :=
    { numVars := case.numVars
    , numConstraints := case.numConstraints
    , c := cUser
    , a := case.a
    , rowBounds := case.rowBounds
    , colBounds := case.colBounds
    , objOffset := 0 }
  match validate p with
  | .error e => .fail s!"validate failed: {repr e}"
  | .ok pV =>
    match solveExact (noPresolve sense) p with
    | .error e => .fail s!"solveExact failed: {repr e}"
    | .ok sol =>
      let pCanon := canonicalize sense pV
      match sol.status, sol.certificate.primal, sol.certificate.dual, sol.objective with
      | .optimal, some x, some d, some obj =>
        let parts : Array String := Id.run do
          let mut errs : Array String := #[]
          match case.expectedX with
          | some ex => if x.toArray != ex then errs := errs.push s!"x: expected {repr ex}, got {repr x}"
          | none => pure ()
          if obj != expectedObjUser then
            errs := errs.push s!"obj: expected {repr expectedObjUser}, got {repr obj}"
          if !dualEq d case.expectedDual then
            errs := errs.push s!"dual: expected {repr case.expectedDual}, got {repr d}"
          if !checkOptimal pCanon x.toArray d then
            errs := errs.push s!"checkOptimal returned false on pCanon={repr pCanon}, x={repr x}, d={repr d}"
          pure errs
        if parts.isEmpty then .ok
        else .fail (String.intercalate "; " parts.toList)
      | st, _, _, _ =>
        .fail s!"expected .optimal, got {repr st}: solution = {repr sol}"

/-! ## Case definitions.

  Every case is a one-row, one-variable LP, `A = [[1]]`, with `x` the
  single decision variable so that `(Ax)₀ = x` and stationarity for the
  canonical (min) form reduces to

      `cCanon = (yL − yU) + (zL − zU)`

  which we use to derive each `expectedDual` by hand.

  Conventions for SoPlex 8.0.2 (cross-checked by `runOne`):

  * `getDualRational` returns the signed row dual `y`. The bridge
    splits via `split_pos`: `y > 0 → rowLower = y`, `y < 0 → rowUpper = -y`.
  * `getRedCostRational` returns the signed reduced cost `z`. Same
    split: `z > 0 → colLower = z`, `z < 0 → colUpper = -z`.
  * Free coordinates (`none` bound) come back as `0` from SoPlex and
    therefore land in both halves as `0`.
-/

/-- Helper: a `DualBundle` for one-row one-col problems. -/
private def db (rL rU cL cU : Rat) : DualBundle 1 1 :=
  { rowLower := #v[rL], rowUpper := #v[rU], colLower := #v[cL], colUpper := #v[cU] }

private def A1 : Array (Nat × Nat × Rat) := #[(0, 0, 1)]

/-- Free row × free col, `c = 0`. Every `x` is feasible and optimal,
    so we do not assert a specific primal value — only that the
    canonical dual is all-zero. -/
private def C_free_free : CoreCase :=
  { name := "free-row × free-col"
  , numVars := 1, numConstraints := 1
  , cCanon := #[0], a := A1
  , rowBounds := #[(none, none)]
  , colBounds := #[(none, none)]
  , expectedX := none
  , expectedObjCanon := 0
  , expectedDual := db 0 0 0 0 }

/-- Free row × fixed col `x = 2`, `c = 1`. Stationarity → `zL - zU = 1`;
    `x` is non-basic (fixed both sides), SoPlex returns `z = c = 1 > 0`. -/
private def C_free_fixed : CoreCase :=
  { name := "free-row × fixed-col"
  , numVars := 1, numConstraints := 1
  , cCanon := #[1], a := A1
  , rowBounds := #[(none, none)]
  , colBounds := #[(some 2, some 2)]
  , expectedX := some #[2]
  , expectedObjCanon := 2
  , expectedDual := db 0 0 1 0 }

/-- Free row × lower-only col `x ≥ 2`, `c = 1`. Optimum at the lower bound. -/
private def C_free_lo : CoreCase :=
  { name := "free-row × lower-only-col"
  , numVars := 1, numConstraints := 1
  , cCanon := #[1], a := A1
  , rowBounds := #[(none, none)]
  , colBounds := #[(some 2, none)]
  , expectedX := some #[2]
  , expectedObjCanon := 2
  , expectedDual := db 0 0 1 0 }

/-- Free row × upper-only col `x ≤ 3`, `c = -1`. Optimum at the upper bound. -/
private def C_free_hi : CoreCase :=
  { name := "free-row × upper-only-col"
  , numVars := 1, numConstraints := 1
  , cCanon := #[-1], a := A1
  , rowBounds := #[(none, none)]
  , colBounds := #[(none, some 3)]
  , expectedX := some #[3]
  , expectedObjCanon := -3
  , expectedDual := db 0 0 0 1 }

/-- Free row × boxed col `1 ≤ x ≤ 5`, `c = 1`. Optimum at the lower
    bound; upper-bound multiplier is zero. -/
private def C_free_boxed : CoreCase :=
  { name := "free-row × boxed-col"
  , numVars := 1, numConstraints := 1
  , cCanon := #[1], a := A1
  , rowBounds := #[(none, none)]
  , colBounds := #[(some 1, some 5)]
  , expectedX := some #[1]
  , expectedObjCanon := 1
  , expectedDual := db 0 0 1 0 }

/-- Equality row `x = 2` × lower-only col `x ≥ 0`, `c = 1`. Row binds;
    col bound is slack (`2 > 0`). Stationarity → `y = 1 > 0`, lands in
    `rowLower`. -/
private def C_eq_lo : CoreCase :=
  { name := "equality-row × lower-only-col"
  , numVars := 1, numConstraints := 1
  , cCanon := #[1], a := A1
  , rowBounds := #[(some 2, some 2)]
  , colBounds := #[(some 0, none)]
  , expectedX := some #[2]
  , expectedObjCanon := 2
  , expectedDual := db 1 0 0 0 }

/-- Equality row `x = 2` × upper-only col `x ≤ 5`, `c = 1`. -/
private def C_eq_hi : CoreCase :=
  { name := "equality-row × upper-only-col"
  , numVars := 1, numConstraints := 1
  , cCanon := #[1], a := A1
  , rowBounds := #[(some 2, some 2)]
  , colBounds := #[(none, some 5)]
  , expectedX := some #[2]
  , expectedObjCanon := 2
  , expectedDual := db 1 0 0 0 }

/-- Equality row `x = 2` × boxed col `0 ≤ x ≤ 5`, `c = 1`. -/
private def C_eq_boxed : CoreCase :=
  { name := "equality-row × boxed-col"
  , numVars := 1, numConstraints := 1
  , cCanon := #[1], a := A1
  , rowBounds := #[(some 2, some 2)]
  , colBounds := #[(some 0, some 5)]
  , expectedX := some #[2]
  , expectedObjCanon := 2
  , expectedDual := db 1 0 0 0 }

/-- Lower-only row `x ≥ 1` × lower-only col `x ≥ 0`, `c = 1`. -/
private def C_lo_lo : CoreCase :=
  { name := "lower-only-row × lower-only-col"
  , numVars := 1, numConstraints := 1
  , cCanon := #[1], a := A1
  , rowBounds := #[(some 1, none)]
  , colBounds := #[(some 0, none)]
  , expectedX := some #[1]
  , expectedObjCanon := 1
  , expectedDual := db 1 0 0 0 }

/-- Lower-only row `x ≥ 1` × upper-only col `x ≤ 5`, `c = 1`. -/
private def C_lo_hi : CoreCase :=
  { name := "lower-only-row × upper-only-col"
  , numVars := 1, numConstraints := 1
  , cCanon := #[1], a := A1
  , rowBounds := #[(some 1, none)]
  , colBounds := #[(none, some 5)]
  , expectedX := some #[1]
  , expectedObjCanon := 1
  , expectedDual := db 1 0 0 0 }

/-- Lower-only row `x ≥ 1` × boxed col `0 ≤ x ≤ 5`, `c = 1`. -/
private def C_lo_boxed : CoreCase :=
  { name := "lower-only-row × boxed-col"
  , numVars := 1, numConstraints := 1
  , cCanon := #[1], a := A1
  , rowBounds := #[(some 1, none)]
  , colBounds := #[(some 0, some 5)]
  , expectedX := some #[1]
  , expectedObjCanon := 1
  , expectedDual := db 1 0 0 0 }

/-- Upper-only row `x ≤ 3` × lower-only col `x ≥ 0`, `c = -1`. Row binds
    at upper, SoPlex's signed `y = -1 < 0`, lands in `rowUpper`. -/
private def C_hi_lo : CoreCase :=
  { name := "upper-only-row × lower-only-col"
  , numVars := 1, numConstraints := 1
  , cCanon := #[-1], a := A1
  , rowBounds := #[(none, some 3)]
  , colBounds := #[(some 0, none)]
  , expectedX := some #[3]
  , expectedObjCanon := -3
  , expectedDual := db 0 1 0 0 }

/-- Upper-only row `x ≤ 3` × upper-only col `x ≤ 5`, `c = -1`. -/
private def C_hi_hi : CoreCase :=
  { name := "upper-only-row × upper-only-col"
  , numVars := 1, numConstraints := 1
  , cCanon := #[-1], a := A1
  , rowBounds := #[(none, some 3)]
  , colBounds := #[(none, some 5)]
  , expectedX := some #[3]
  , expectedObjCanon := -3
  , expectedDual := db 0 1 0 0 }

/-- Upper-only row `x ≤ 3` × boxed col `0 ≤ x ≤ 5`, `c = -1`. -/
private def C_hi_boxed : CoreCase :=
  { name := "upper-only-row × boxed-col"
  , numVars := 1, numConstraints := 1
  , cCanon := #[-1], a := A1
  , rowBounds := #[(none, some 3)]
  , colBounds := #[(some 0, some 5)]
  , expectedX := some #[3]
  , expectedObjCanon := -3
  , expectedDual := db 0 1 0 0 }

/-- Ranged row `1 ≤ x ≤ 3` × lower-only col `x ≥ 0`, `c = 1`. Optimum at
    the row's lower bound; upper-side row multiplier is zero. -/
private def C_ranged_lo : CoreCase :=
  { name := "ranged-row × lower-only-col"
  , numVars := 1, numConstraints := 1
  , cCanon := #[1], a := A1
  , rowBounds := #[(some 1, some 3)]
  , colBounds := #[(some 0, none)]
  , expectedX := some #[1]
  , expectedObjCanon := 1
  , expectedDual := db 1 0 0 0 }

/-- Ranged row `1 ≤ x ≤ 3` × upper-only col `x ≤ 5`, `c = 1`. -/
private def C_ranged_hi : CoreCase :=
  { name := "ranged-row × upper-only-col"
  , numVars := 1, numConstraints := 1
  , cCanon := #[1], a := A1
  , rowBounds := #[(some 1, some 3)]
  , colBounds := #[(none, some 5)]
  , expectedX := some #[1]
  , expectedObjCanon := 1
  , expectedDual := db 1 0 0 0 }

/-- Ranged row `1 ≤ x ≤ 3` × boxed col `0 ≤ x ≤ 5`, `c = 1`. -/
private def C_ranged_boxed : CoreCase :=
  { name := "ranged-row × boxed-col"
  , numVars := 1, numConstraints := 1
  , cCanon := #[1], a := A1
  , rowBounds := #[(some 1, some 3)]
  , colBounds := #[(some 0, some 5)]
  , expectedX := some #[1]
  , expectedObjCanon := 1
  , expectedDual := db 1 0 0 0 }

/-! ### Supplemental cases beyond the 17-cell matrix.

  The cell-by-cell goldens above all use `A = [[1]]` and a positive
  row-bound side binding at the optimum. These extra cases exercise:

  * Non-unit `A` (`+2` and `-1`), so the stationarity equation
    `c = Aᵀy + z` involves a non-trivial multiplier on the row dual.
  * A ranged row binding at its *upper* side, complementary to the
    lower-binding ranged cases above.
  * A multi-row, multi-column LP where both a row dual and a column
    reduced cost are simultaneously nonzero. -/

/-- Ranged row `1 ≤ x ≤ 3` × lower-only col `x ≥ 0`, `c = −1`. Pushes
    `x` up against the row's upper bound; SoPlex returns `y = −1 < 0`,
    landing in `rowUpper`. Complementary to `C_ranged_lo`. -/
private def C_ranged_upper_binding : CoreCase :=
  { name := "ranged-row × lower-only-col (upper-binding)"
  , numVars := 1, numConstraints := 1
  , cCanon := #[-1], a := A1
  , rowBounds := #[(some 1, some 3)]
  , colBounds := #[(some 0, none)]
  , expectedX := some #[3]
  , expectedObjCanon := -3
  , expectedDual := db 0 1 0 0 }

/-- Lower-only row `2x ≥ 4` × lower-only col `x ≥ 0`, `c = 1`. Tests
    a non-unit positive matrix entry: stationarity gives
    `1 = 2 · y + 0`, so `y = 1/2`. Lands in `rowLower` (`y > 0`). -/
private def C_nonunit_pos : CoreCase :=
  { name := "non-unit A=+2: lower-only-row × lower-only-col"
  , numVars := 1, numConstraints := 1
  , cCanon := #[1]
  , a := #[(0, 0, 2)]
  , rowBounds := #[(some 4, none)]
  , colBounds := #[(some 0, none)]
  , expectedX := some #[2]
  , expectedObjCanon := 2
  , expectedDual := db (1/2) 0 0 0 }

/-- Upper-only row `−x ≤ −2` (i.e. `x ≥ 2`) × lower-only col `x ≥ 0`,
    `c = 1`. Tests a negative matrix entry. Stationarity:
    `1 = (-1)·(y_lo − y_hi) + (z_lo − z_hi)`. The active row bound
    here is the *upper* side of `−x ≤ −2`, so SoPlex returns `y < 0`;
    with `A = -1` the bridge lands the multiplier in `rowUpper = 1`. -/
private def C_nonunit_neg : CoreCase :=
  { name := "non-unit A=−1: upper-only-row × lower-only-col"
  , numVars := 1, numConstraints := 1
  , cCanon := #[1]
  , a := #[(0, 0, -1)]
  , rowBounds := #[(none, some (-2))]
  , colBounds := #[(some 0, none)]
  , expectedX := some #[2]
  , expectedObjCanon := 2
  , expectedDual := db 0 1 0 0 }

/-- Two variables, two equality rows, `c = (1, 2)`:

      `x + y = 3,  x = 1`,   `x ≥ 0,  y ≥ 0`.

    Forces `x = 1, y = 2`. Column `y` is basic (interior of its
    bound), but column `x` sits at its only-effective constraint
    via the second equality. Hand-computed dual via stationarity:

      `c₁ = 1 = y₁·1 + y₂·1 + z_x → y₁ + y₂ = 1` (since `z_x = 0`
        when we choose the natural basis with `x` basic too — both
        columns lie strictly inside their col bounds).
      `c₂ = 2 = y₁·1 + 0       →  y₁ = 2`,  so `y₂ = −1`.

    Both row duals are nonzero; the second is negative (lands in
    `rowUpper`). Verifies that the per-row `split_pos` works
    independently across rows. -/
private def C_two_row_dual : CoreCase :=
  { name := "two-row equality system with mixed-sign duals"
  , numVars := 2, numConstraints := 2
  , cCanon := #[1, 2]
  , a := #[(0, 0, 1), (0, 1, 1), (1, 0, 1)]
  , rowBounds := #[(some 3, some 3), (some 1, some 1)]
  , colBounds := #[(some 0, none), (some 0, none)]
  , expectedX := some #[1, 2]
  , expectedObjCanon := 5
  , expectedDual :=
      { rowLower := #v[2, 0], rowUpper := #v[0, 1]
      , colLower := #v[0, 0], colUpper := #v[0, 0] } }

/-- Two variables, one lower-only row, one boxed column, one
    lower-only column, `c = (1, 1)`:

      `x + y ≥ 2`,   `0 ≤ x ≤ 1`,   `y ≥ 0`.

    Optimum at `x = 1, y = 1`: the column upper bound on `x` is
    active *and* the row lower bound is active *and* the reduced
    cost on `y` is positive (its lower bound is active in a basic
    sense — but the second equality of stationarity ties `z_y` to
    `y_row`). Hand computation:

      `c_y = 1 = y_row · 1 + z_y → z_y = 1 - y_row`.
      `c_x = 1 = y_row · 1 + (z_x_lo − z_x_hi)`.

    The optimal basis takes `y` basic (interior, `z_y = 0`), forcing
    `y_row = 1`; then `z_x_lo − z_x_hi = 0`, and with the upper bound
    of `x` active, the conventional split is `z_x_hi = 0, z_x_lo = 0`
    (column `x` is also at its bound with zero reduced cost — a
    legitimate degenerate situation). This case checks that SoPlex /
    the bridge agree on which non-zero multiplier goes where when
    multiple multipliers could in principle absorb the same residual.

    Note: this case is intentionally an integration check beyond the
    cell matrix; the exact dual SoPlex returns is empirically
    pinned. -/
private def C_two_var_mixed : CoreCase :=
  { name := "two-var: lower-only-row + boxed-col + lower-only-col"
  , numVars := 2, numConstraints := 1
  , cCanon := #[1, 1]
  , a := #[(0, 0, 1), (0, 1, 1)]
  , rowBounds := #[(some 2, none)]
  , colBounds := #[(some 0, some 1), (some 0, none)]
  , expectedX := some #[1, 1]
  , expectedObjCanon := 2
  , expectedDual :=
      { rowLower := #v[1], rowUpper := #v[0]
      , colLower := #v[0, 0], colUpper := #v[0, 0] } }

private def coreCases : Array CoreCase := #[
  C_free_free, C_free_fixed, C_free_lo, C_free_hi, C_free_boxed,
  C_eq_lo, C_eq_hi, C_eq_boxed,
  C_lo_lo, C_lo_hi, C_lo_boxed,
  C_hi_lo, C_hi_hi, C_hi_boxed,
  C_ranged_lo, C_ranged_hi, C_ranged_boxed,
  -- supplemental
  C_ranged_upper_binding,
  C_nonunit_pos, C_nonunit_neg,
  C_two_row_dual, C_two_var_mixed
]

def main : IO UInt32 := do
  let mut failed : Nat := 0
  let mut total : Nat := 0
  for c in coreCases do
    for sense in #[ObjSense.minimize, ObjSense.maximize] do
      total := total + 1
      let label := s!"{c.name} [{repr sense}]"
      match runOne c sense with
      | .ok => IO.println s!"[ok]   {label}"
      | .fail msg =>
        failed := failed + 1
        IO.println s!"[FAIL] {label}: {msg}"
  if failed = 0 then
    IO.println s!"All {total} accessor golden tests passed."
    return 0
  else
    IO.eprintln s!"{failed} of {total} accessor golden tests FAILED."
    return 1

end AccessorGoldens

def main : IO UInt32 := AccessorGoldens.main
